isDeepEqual_first
StolpnerA/js--FE2-TMS-course pull request #10
Opened 2020-04-17 22:11 UTC by arhipy97

в 3 уроке isDeepEqual

2020-04-26 22:17 UTC, arhipy97 commented
kalendar + isDeepEqual

2020-04-29 18:21 UTC, StolpnerA requested changes

2020-04-29 18:21 UTC, StolpnerA commented on 02/ht/README.md
> -## Что вам понадобится
Для чего удалил мой файл? :)

2020-04-29 18:21 UTC, StolpnerA commented on 02/ht/arhipy97/doc.md
> +### Что такое API? Примеры?
Чего не ответил? )

2020-04-29 18:21 UTC, StolpnerA commented on 02/ht/arhipy97/doc.md
> +### Как в js реализовать многопоточность?
Где ответ? )

2020-04-29 18:21 UTC, StolpnerA commented on 03/ht/arhipy97/isDeepEqual/isDeepEqual.html
> +                return(false)
Для чего обернул в круглые скобки?

2020-04-29 18:21 UTC, StolpnerA commented on 03/ht/arhipy97/isDeepEqual/isDeepEqual.html
> +            if( typeof(a) == "object"){
Я говорил всегда стараться использовать строгое сравнение

2020-04-29 18:21 UTC, StolpnerA commented on 03/ht/arhipy97/isDeepEqual/isDeepEqual.html
> +                    }
Выравнивание сделай нормальное по всему коду

2020-04-29 18:21 UTC, StolpnerA commented on 03/ht/arhipy97/kalendar/JS/script.js
> +let DaysQuantity = new Date ( year, month , 0);
Почему переменная с большой буквы?

2020-04-29 18:21 UTC, StolpnerA commented on 03/ht/arhipy97/kalendar/JS/script.js
> +let kd = new Date (year, month - 1,);
Что за название такое `kd`? :)

2024-06-18 13:34 UTC, closed without merging